cart/urls.py
from django.urls import path
from cart.views import add_to_cart, cart, checkout, hx_menu_cart, update_cart, hx_cart_total, success

urlpatterns = [
    path('add_to_cart/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('cart', cart, name='cart'),
    path('cart/checkout', checkout, name='checkout'),
    path('hx_menu_cart', hx_menu_cart, name='hx_menu_cart'),
    path('update_cart/<int:product_id>/<str:action>', update_cart, name='update_cart'),
    path('hx_cart_total', hx_cart_total, name='hx_cart_total'),
    path('cart/success', success, name='success')
   
]

ecomsite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
import core.urls
import product.urls
import cart.urls
import order.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(core.urls)),
    path('', include(product.urls)),
    path('', include(cart.urls)),
    path('', include(order.urls))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

product/urls.py
from django.urls import path
from product.views import product


urlpatterns = [
    path('shop/<slug:slug>/', product, name='product'),
   
]

product/models.py
from django.db import models
from PIL import Image
from io import BytesIO
from django.core.files import File
from django.utils.text import slugify
from django.urls import reverse


class Category(models.Model):
    name= models.CharField(max_length=255)
    slug = models.SlugField()

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products',on_delete=models.CASCADE)
    name= models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    description =  models.TextField()
    price=models.FloatField()
    created_at=models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='uploads/', blank=True, null=True)
    thumbnail=models.ImageField(upload_to='uploads/', blank=True, null=True)



    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return self.name

    def get_thumbnail(self):
        if self.thumbnail:
            return self.thumbnail.url 
        else:
            if self.image:
                self.thumbnail = self.make_thumbnail(self.image)
                self.save()

                return self.thumbnail.url
            else:
                return 'https://via.placeholder.com/240x240x.jpg'
    
    def make_thumbnail(self, image, size=(300,300)):
        img = Image.open(image)
        img.convert('RGB')
        img.thumbnail(size)

        thumb_io = BytesIO()
        img.save(thumb_io, 'JPEG', quality=85)

        thumbnail = File(thumb_io, name=image.name)

        return thumbnail
    
    def save(self, *args, **kwargs):
        self.slug = self.slug or slugify(self.name)
        super().save(*args, **kwargs)
    
    

class ProductImages(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="staticfiles/admin/img/")


    def __str__(self):
        return self.product.name

product/views.py
from django.shortcuts import get_object_or_404, render
from .models import Product


def product(request, slug):
    product = get_object_or_404(Product, slug=slug)
    related_products = Product.objects.filter(category=product.category).exclude(id=product.id)[:3]
    return render(request, 'product/product.html', {'product':product, 'related_products':related_products})

product/templates/product/product.html
{% extends "core/base.html" %}

{% block title %}{{product.name}} |{% endblock title %}

{% block frontpagecontent %}

<div class="max-w-6xl w-full mx-auto flex flex-wrap py-2 px-6 xl:px-0 mt-5">  

    <div class='images w-full mb-6 lg:mb-0 lg:w-3/5 '>
        
        <img src="{% if product.image %}{{ product.image.url}}
        {% else %}
        https://via.placeholder.com/240x240x.jpg
        {% endif %}" 
        alt="" class="rounded-xl object-cover h-96 w-full">

        <div class='container grid grid-cols-3 gap-1 mx-auto images w-1/4 mt-4 mb-5 lg:mb-0 lg:w-3/5 '>
        
            
        
       {% for prodimg in product.productimages_set.all %}
        <img src="{% if prodimg.image %}{{ prodimg.image.url}}
        {% else %}
        https://via.placeholder.com/240x240x.jpg
        {% endif %}" 
        alt="" class="rounded-xl object-cover h-40 w-76">
         
           {% endfor %} 
           
            
    
        </div>
    </div>
    
    <div class='information w-full lg:w-2/5 lg:p-6'>
        <h1 class="text-2xl">{{product.name}}</h1>
        <p class='mt-1 text-blue-900'>${{product.price}}</p>
        {% if product.description %}
            <p class='mt-5 text-blue-900'>
                {{product.description}}
            </p>
        {% endif %}

    <a href="#" 
        class="mt-6 inline-block px-8 py-4 rounded-xl bg-blue-600 text-white hover:bg-blue-900"
        hx-get="{% url 'add_to_cart' product.id %}" 
        hx-target="#menu-cart-button"
        hx-swap='outerHTML'
        >
        Add to cart
    </a>
    </div>
    
</div>


<h1 class='text-center mt-10 text-xl text-blue-600 font-bold'>
    Similar Products
</h1>


<div class="w-full py-4  xl:px-0 mt-1 mb-1 ">   
    <div class="products w-full lg:w-full -mt-4 flex items-center flex-wrap justify-center">
        
{% for product in related_products %}
<div class='w-full md:w-1/2 xl:w-1/4 shadow-lg ml-8 mr-2 mb-5 mt-5 p-6'>


    <a href="{% url 'product' product.slug %}" >
    <img src="{{ product.get_thumbnail}}" alt="" class="rounded-xl hover:shadow-lg object-cover h-48 w-96">
    </a>                                                                                                                                                                                        
<div class="pt-3 flex items-center justify-between">


    <a href="{% url 'product' product.slug %}">
        {{product.name}}

    </a>

    <a href="" 
    hx-get="{% url 'add_to_cart' product.id %}" 
    hx-target="#menu-cart-button"
    hx-swap='outerHTML'
    class="text-blue-500 hover:text-blue-900">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-7 w-7" viewBox="0 0 20 20" fill="currentColor">
            <path d="M3 1a1 1 0 000 2h1.22l.305 1.222a.997.997 0 00.01.042l1.358 5.43-.893.892C3.74 11.846 4.632 14 6.414 14H15a1 1 0 000-2H6.414l1-1H14a1 1 0 00.894-.553l3-6A1 1 0 0017 3H6.28l-.31-1.243A1 1 0 005 1H3zM16 16.5a1.5 1.5 0 11-3 0 1.5 1.5 0 013 0zM6.5 18a1.5 1.5 0 100-3 1.5 1.5 0 000 3z" />
          </svg>
    </a>
</div>




<p class="pt-2 text-blue-500 font-bold">${{product.price}}</p>




</div>
{% endfor %}

</div>
</div>

{% endblock frontpagecontent %}